-app-name = Kontoj
-app-author = Antoine Turmel

json-config-path = Path to config json:
json-config-load = Load
    .title = Load JSON config file
json-config-save = Save
    .title = Save JSON config in browser
json-config-clear = Clear
    .title = Remove JSON config from browser
json-no-file-selected = No file selected!
new-list-warning = Loading a new services list will erase any data generated on this page, continue?
general-lastname = Last name:
general-firstname = First name:
general-email = Email:
general-fill-email =
    .title = Fill all email fields
general-empty-email = User Email is empty!
general-no-services-checked = No service selected!
general-group = Group:
general-actions = Actions:
general-generate-password =
    .title = Generate passwords for all services checked
general-generate-mail =
    .title = Generate credentials summary
general-fill-all =
    .title = Fill e-mail & password
general-help =
    .title = Help
general-settings =
    .title = Settings
general-companion =
    .title = Kontoj Companion
general-about-kontoj = 
    .title = About { -app-name }
about-version = Version
about-releasenotes = Release notes
about-author = Developed by { -app-author }
about-host = Hosted by
about-license = Project under license
about-donate = You can help the project by doing a donation here:
about-thanks = Thanks !
settings-mailto-type = Mail body setting
settings-mailto-body-indication = (Compatible with most mail service and software)
settings-mailto-htmlbody-indication = (Compatible with Mozilla Thunderbird)
settings-theme-scheme = Color Theme
settings-theme-system = System
settings-theme-light = Light
settings-theme-dark = Dark
settings-labelbutton-type = Display label on buttons
settings-labelbutton-display = Display
settings-labelbutton-hide = Hide
settings-override-config = Override list configuration
setting-override-enable = Enable
setting-override-disable = Disable
setting-override-subjectmail = Mail subject
setting-override-bodymailstart = Mail start
setting-override-bodymailend = Mail end
setting-override-passwordlength = Password Length
setting-override-passwordchars = Characters used to generate the password
setting-override-subjectmail-input =
    .placeholder = Credentials for _firstname_ _lastname_
setting-override-bodymailstart-input =
    .placeholder = Hello _firstname_ _lastname_, here are your credentials down below:
setting-override-bodymailend-input =
    .placeholder = Have a nice day
settings-dialog-save = Save
service-email =
    .placeholder = email
service-password =
    .placeholder = password
service-login =
    .placeholder = login
service-generate-password = 
    .title = Generate Password
service-unlock-password =
    .title = Unlock Password field
service-login-google-account = Connection using Google Account
service-action-login =
    .title = Login
service-action-create-account =
    .title = Create Account
service-mailbody-url = URL:
service-mailbody-email = Email:
service-mailbody-login = Login:
service-mailbody-password = Password:
help-documentation-url = You can find the documentation of Kontoj in the README.md here:
help-try-kontoj = You can try Kontoj by downloading the sample file above and open it on the top bar by clicking on Browse...
campanion-intro = <b>Kontoj Companion</b>, is an « Userscript » made to help you autofill data like email/password in your services fields.
companion-addon-install = To install it, you first need a browser extension like <a data-l10n-name="violentmonkey-url">Violentmonkey</a> or <a data-l10n-name="tampermonkey-url">Tampermonkey</a> installed.
companion-userscript-install = Next, open the URL below and install the script.
companion-note = Note: Data is stored only in the browser extension, no data is sent to 3rd party using this script.
welcome-title = Welcome!
welcome-begin = To begin with, open your services JSON file on the top bar.
welcome-examplefile = Example file: