-app-name = Kontoj
-app-author = Antoine Turmel

json-config-path = Path to config json:
json-config-load = Load
    .title = Load JSON config file
json-config-save = Save
    .title = Save JSON config in browser
json-config-clear = Clear
    .title = Remove JSON config from browser
general-lastname = Last name:
general-firstname = First name:
general-email = Email:
general-fill-email =
    .title = Fill all email fields
general-empty-email = User Email is empty!
general-no-services-checked = No service selected!
general-group = Group:
general-actions = Actions:
general-generate-password =
    .title = Generate passwords for all services checked
general-generate-mail = 
    .title = Generate mail for the user
general-help =
    .title = Help
general-about-kontoj = 
    .title = About { -app-name }
about-version = version
about-author = developed by { -app-author }
service-email =
    .placeholder = email
service-password =
    .placeholder = password
service-login =
    .placeholder = login
service-generate-password = 
    .title = Generate Password
service-unlock-password =
    .title = Unlock Password field
service-login-google-account = Connection using Google Account
service-action-login =
    .title = Login
service-action-create-account =
    .title = Create Account
service-mailbody-url = URL:
service-mailbody-email = Email:
service-mailbody-login = Login:
service-mailbody-password = Password:
help-documentation-url = You can find the documentation of Kontoj in the README.md here:
help-try-kontoj = You can try Kontoj by downloading this sample file above and open it on the top bar by clicking on Browse... then using Load button.