-app-name = Kontoj
-app-author = Antoine Turmel

json-config-path = Chemin vers le fichier de config json :
json-config-load = Charger
    .title = Charger le fichier JSON de config
json-config-save = Enregistrer
    .title = Enregistrer le chemin du fichier de configuration JSON dans le navigateur
json-config-clear = Effacer
    .title = Effacer le chemin du fichier de configuration JSON stocké dans le navigateur
general-lastname = Nom :
general-firstname = Prénom :
general-email = E-mail:
general-fill-email =
    .title = Remplir tous les champs email
general-empty-email = L'adresse mail de l'utilisateur est vide !
general-no-services-checked = Aucun service sélectionné !
general-group = Groupe :
general-actions = Actions :
general-generate-password =
    .title = Générer les mots de passe pour tous les services cochés
general-generate-mail = 
    .title = Générer le mail à envoyer à l'utilisateur
general-help =
    .title = Aide
general-about-kontoj = 
    .title = À propos de { -app-name }
about-version = version
about-author = développé par { -app-author }
service-email =
    .placeholder = e-mail
service-password =
    .placeholder = mot de passe
service-login =
    .placeholder = identifiant
service-generate-password = 
    .title = Générer le mot de passe
service-unlock-password =
    .title = Déverrouiller le champ mot de passe
service-login-google-account =  Connexion avec les identifiants Gmail
service-action-login =
    .title = Connexion
service-action-create-account =
    .title = Créer un compte
service-mailbody-url = URL :
service-mailbody-email = Email :
service-mailbody-login = Login :
service-mailbody-password = Mot de passe :
help-documentation-url = Vous trouverez la documentation de Kontoj (en anglais pour le moment) dans le README.md ici :
help-try-kontoj = Vous pouvez essayer Kontoj en téléchargeant ce fichier en dessous et en l'ouvrant dans la barre du haut en cliquant sur Parcourir... puis en cliquant sur le bouton "Charger".