-app-name = Kontoj
-app-author = Antoine Turmel

json-config-path = Chemin vers le fichier de config json :
json-config-load = Charger
    .title = Charger le fichier JSON de config
json-config-save = Enregistrer
    .title = Enregistrer le chemin du fichier de configuration JSON dans le navigateur
json-config-clear = Effacer
    .title = Effacer le chemin du fichier de configuration JSON stocké dans le navigateur
json-no-file-selected = Aucun fichier sélectionné !
general-lastname = Nom :
general-firstname = Prénom :
general-email = E-mail:
general-fill-email =
    .title = Remplir tous les champs email
general-empty-email = L'adresse mail de l'utilisateur est vide !
general-no-services-checked = Aucun service sélectionné !
general-group = Groupe :
general-actions = Actions :
general-generate-password =
    .title = Générer les mots de passe pour tous les services cochés
general-generate-mail = 
    .title = Générer le mail à envoyer à l'utilisateur
general-help =
    .title = Aide
general-settings =
    .title = Paramètres
general-companion =
    .title = Companion Kontoj
general-about-kontoj = 
    .title = À propos de { -app-name }
about-version = version
about-author = développé par { -app-author }
about-donate = Vous pouvez aider le projet en faisant un don ici :
about-thanks = Merci !
settings-mailto-type = Paramètre du contenu du mail
settings-mailto-body-indication = (Compatible avec la plupart des services et logiciel de messagerie)
settings-mailto-htmlbody-indication = (Compatible avec Mozilla Thunderbird)
settings-dialog-save = Enregistrer
service-email =
    .placeholder = e-mail
service-password =
    .placeholder = mot de passe
service-login =
    .placeholder = identifiant
service-generate-password = 
    .title = Générer le mot de passe
service-unlock-password =
    .title = Déverrouiller le champ mot de passe
service-login-google-account =  Connexion avec les identifiants Gmail
service-action-login =
    .title = Connexion
service-action-create-account =
    .title = Créer un compte
service-mailbody-url = URL :
service-mailbody-email = Email :
service-mailbody-login = Login :
service-mailbody-password = Mot de passe :
help-documentation-url = Vous trouverez la documentation de Kontoj (en anglais pour le moment) dans le README.md ici :
help-try-kontoj = Vous pouvez essayer Kontoj en téléchargeant ce fichier en dessous et en l'ouvrant dans la barre du haut en cliquant sur Parcourir... puis en cliquant sur le bouton "Charger".
campanion-intro = <b>Companion Kontoj</b> est un « Userscript » conçu pour vous aider à auto-compléter les données telles que l'email ou le mot de passe dans les champs de vos services.
companion-addon-install = Pour l'installer, vous avez d'abord besoin d'installer une extension navigateur comme <a data-l10n-name="violentmonkey-url">Violentmonkey</a> ou <a data-l10n-name="tampermonkey-url">Tampermonkey</a>.
companion-userscript-install = Ensuite, ouvrez le lien ci-dessous pour installer le script.
companion-note = Remarque : Les données sont stockées seulement dans l'extension navigateur, aucune information n'est transmise à une source tierce en utilisant ce script.
welcome-title = Bienvenue !
welcome-begin = Pour commencer, ouvrez et chargez votre fichier JSON de services dans la barre du haut. Fichier exemple :