-app-name = Kontoj
-app-author = Antoine Turmel

json-config-path = Chemin vers le fichier de config json :
json-config-load = Charger
    .title = Charger le fichier JSON de config
json-config-save = Enregistrer
    .title = Enregistrer le chemin du fichier de configuration JSON dans le navigateur
json-config-clear = Effacer
    .title = Effacer le chemin du fichier de configuration JSON stocké dans le navigateur
json-no-file-selected = Aucun fichier sélectionné !
new-list-warning = En chargeant une nouvelle liste de services les données générées sur cette page seront perdues, souhaitez-vous continuer ?
pro-features-reload = Pour activer ou désactiver les fonctionnalités Pro ou changer le token, la page doit être rechargée, continuer ?
pro-encrypted-file-warning = Ce fichier liste est chiffré, obtenez un compte Pro pour le déchiffrer et le charger.
general-lastname = Nom :
general-firstname = Prénom :
general-email = E-mail:
general-fill-email =
    .title = Remplir tous les champs email
general-empty-email = L'adresse mail de l'utilisateur est vide !
general-no-services-checked = Aucun service sélectionné !
general-group = Groupe :
general-actions = Actions :
general-generate-password =
    .title = Générer les mots de passe pour tous les services cochés
general-generate-mail = 
    .title = Générer le mail avec les accès
general-fill-all =
    .title = Remplir l'adresse mail & mot de passe
general-help =
    .title = Aide
general-settings =
    .title = Paramètres
general-companion =
    .title = Companion Kontoj
general-pro =
    .title = Pro
general-about-kontoj = 
    .title = À propos de { -app-name }
about-version = Version
about-releasenotes = Notes de version
about-author = Développé par { -app-author }
about-host = Hébergé par
about-service-status = État du service
about-license = Projet sous licence
about-donate = Vous pouvez aider le projet en faisant un don ici :
about-thanks = Merci !
settings-mailto-type = Utiliser html-body pour le contenu du mail
settings-mailto-htmlbody-indication =
    .title = html-body est compatible avec Mozilla Thunderbird, décochez l'option pour les autres services/logiciels de messagerie
settings-theme-scheme = Thème de couleur
settings-theme-system = Système
settings-theme-light = Clair
settings-theme-dark = Sombre
settings-labelbutton-type = Afficher le label des boutons
settings-override-config = Remplacer la configuration de la liste
setting-override-subjectmail = Sujet du mail
setting-override-bodymailstart = Début du mail
setting-override-bodymailend = Fin du mail
setting-override-passwordlength = Longueur du mot de passe
setting-override-passwordchars = Caractères pour générer le mot de passe
setting-override-subjectmail-input =
    .placeholder = Identifiants pour _firstname_ _lastname_
setting-override-bodymailstart-input =
    .placeholder = Bonjour _firstname_ _lastname_, vous trouverez ci-dessous l'ensemble de vos mots de passe :
setting-override-bodymailend-input =
    .placeholder = Bonne journée
settings-pro-account = Activer le compte Pro
setting-pro-token = Token
setting-pro-token-valid = Token valide
setting-pro-token-invalid = Token invalide ou expiré
settings-dialog-save = Enregistrer
service-email =
    .placeholder = e-mail
service-password =
    .placeholder = mot de passe
service-login =
    .placeholder = identifiant
service-generate-password = 
    .title = Générer le mot de passe
service-unlock-password =
    .title = Déverrouiller le champ mot de passe
service-login-third-party =  Connexion avec les identifiants
service-action-login =
    .title = Connexion
service-action-create-account =
    .title = Créer un compte
service-action-no-account-creation =
    .title = Pas de création de compte disponible
service-action-service-status =
    .title = État du service
service-mailbody-url = URL :
service-mailbody-email = Email :
service-mailbody-login = Login :
service-mailbody-password = Mot de passe :
help-documentation-url = Vous trouverez la documentation de Kontoj dans le README.md ici :
help-try-kontoj = Vous pouvez essayer Kontoj en téléchargeant le fichier ci-dessous et en l'ouvrant dans la barre du haut en cliquant sur Parcourir...
campanion-intro = <b>Companion Kontoj</b> est un « Userscript » conçu pour vous aider à auto-compléter les données telles que l'email ou le mot de passe dans les champs de vos services.
companion-addon-install = Pour l'installer, vous avez d'abord besoin d'installer une extension navigateur comme <a data-l10n-name="violentmonkey-url">Violentmonkey</a> ou <a data-l10n-name="tampermonkey-url">Tampermonkey</a>.
companion-userscript-install = Ensuite, ouvrez le lien ci-dessous pour installer le script.
companion-note = Remarque : Les données sont stockées seulement dans l'extension navigateur, aucune information n'est transmise à une source tierce en utilisant ce script.
companion-up-to-date = Le Companion Kontoj est installé et à jour.
companion-outdated = Le Companion Kontoj est installé mais n'est pas à jour, merci de le mettre à jour !
companion-version-installed = Version installée :
companion-version-available = Version disponible :
companion-display-install = Ré-afficher les informations d'installation
whatsnew-version = Vous utilisez désormais la version :
whatsnew-releasenotes = Vous pouvez lire les notes de version ici.
welcome-title = Bienvenue !
welcome-begin = Pour commencer, ouvrez votre fichier JSON de services dans la barre du haut.
welcome-examplefile = Fichier exemple :