# This script deploys your website automatically
name: CI

# Only trigger this script when you push to the main branch
on:
  push:
    branches: [ main ]

permissions:
  contents: write

# Specify the tasks to run when this script gets triggered
jobs:
  build:
    runs-on: ubuntu-latest

    # Download our main branch
    steps:
    - uses: actions/checkout@v2

    - name: Configure Git
      run: |
        git config --global user.email "bot@galaksio.tech"
        git config --global user.name "GitHub bot"

    # Run our deployment command
    - name: Deploying the static website to gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run deploy
